services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
      target: builder
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app
    secrets:
      - db-password
    # ports:
    #   - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
      image: postgres
      restart: always
      user: postgres
      secrets:
        - db-password
      volumes:
        - /var/lib/postgresql/data
      environment:
        - POSTGRES_DB=dev-db-api
        - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      # expose:
      #   - 5432
      ports:
        - "5432:5432"
      healthcheck:
        test: [ "CMD", "pg_isready" ]
        interval: 10s
        timeout: 5s
        retries: 5

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #     PGADMIN_LISTEN_PORT: 80
  #   ports:
  #     - 15432:80
  #   volumes:
  #     - /var/lib/pgadmin
  #   depends_on:
  #     - db

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 8080:8080
    depends_on: 
      - app

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt